# Server
server:
  port: ${PORT}

# Logging
logging:
  level:
    root: WARN
    com.mathisdulieu.ticketing: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%thread] %-5level %logger{36} - %msg%n"

# Swagger
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Services
event-api:
  base-url: ${EVENT_API_BASE_URL}

inventory-api:
  base-url: ${INVENTORY_API_BASE_URL}

reservation-api:
  base-url: ${RESERVATION_API_BASE_URL}
