spring:
  application:
    name: realtime-ticketing-api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

app:
  version: ${APP_VERSION}
  environment: ${APP_ENVIRONMENT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: ${app.version}
    environment: ${app.environment}
