# Server
server:
  port: 8080

# Logging
logging:
  level:
    root: INFO
    com.mathisdulieu.ticketing: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){blue} %clr(%-5level){green} %clr(%logger{36}){cyan} - %msg%n"

# Swagger
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# CORS
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:5173"

# Services
event-api:
  base-url: http://localhost:8081

inventory-api:
  base-url: http://localhost:8082

reservation-api:
  base-url: http://localhost:8083
