name: Push validation

on:
  push:
    branches:
      - main
      - dev
      - feature/**

jobs:
  validate:
    name: Validate API gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Validate project
        run: ./mvnw clean verify